### PR TITLE
Install Sass dependencies via Makefile

### PR DESCRIPTION
**Pull request by xi**
IMHO this approach has some advantages:
- Less manual installation steps
- Sass dependencies are only installed if required
- If bower or node-sass are already used on the system, they are not installed again
- bower and node-sass are in the PATH, so they are easier to use

### CODE REVIEW

**Comment by fabiankirstein** [comment]
Thanks, but I disagree with this approach. I would never rely on the global bower etc. And we do need the bower.json, don't we?

**Comment by xi** [comment]
> And we do need the bower.json, don't we?

Yes. Fixed in c997077.

> I would never rely on the global bower etc.

Each node-sass installation takes up ~26M of disk space. I have about 10 projects that need it. Installing it each time just seems like a waste of disk space to me, especially given the stability of the project.

Here is an idea for a compromise: The Makefile always installs the dependencies with npm, but only if the links in `bin/` do not exist yet. That would allow me to link global installs manually and run `make` after that.

**Comment by fabiankirstein** [comment]
Ok that's fine. But what about the package.json? What if we want to install more npm packages. Actually I don't get why you break the "standard" way of doing all this. :)

**Comment by xi** [comment]
`package.json` is very useful for node projects. In this case, we only use npm to install tools, so it is not as relevant.

**Pull request closed without merging**
